<?php
if (!defined('BASE_PATH')) define('BASE_PATH', dirname(dirname(__FILE__)));
require_once dirname(__DIR__, 2) . '/config/paths.php';
if (!defined('BASE_URL')) define('BASE_URL', SYSTEM_BASE_URL);
require_once BASE_PATH . '/includes/database.php';
$conn = getDBConnection();
if (!$conn) { echo '<div class="alert alert-danger">Database connection failed.</div>'; return; }
$role = strtolower((string)($_SESSION['admin_role'] ?? $_SESSION['role'] ?? 'staff'));
$isAdmin = in_array($role, ['admin','super_admin'], true);
if (!$isAdmin) {
    echo '<div class="alert alert-danger mb-3">Access denied: Admins only.</div>';
    return;
}
$search = trim((string)($_GET['search'] ?? ''));
$status = (string)($_GET['status'] ?? '');
$pageNo = max(1, (int)($_GET['p'] ?? 1));
$limit = 10; $offset = ($pageNo - 1) * $limit;
$where=' WHERE 1=1 '; $params=[]; $types='';
if ($search!=='') { $where .= ' AND (s.name LIKE ? OR s.contact_person LIKE ? OR s.email LIKE ? OR s.phone LIKE ?)'; $t="%$search%"; $params=[$t,$t,$t,$t]; $types='ssss'; }
if ($status!=='' && ($status==='0' || $status==='1')) { $where.=' AND s.is_active=?'; $params[]=(int)$status; $types.='i'; }
$sql="SELECT s.*,COUNT(r.id) product_count,SUM(CASE WHEN r.stock_quantity<=r.reorder_level THEN 1 ELSE 0 END) low_stock_items FROM suppliers s LEFT JOIN remedies r ON s.id=r.supplier_id {$where} GROUP BY s.id ORDER BY s.created_at DESC LIMIT ? OFFSET ?";
$stmt=$conn->prepare($sql); $suppliers=[];
if($stmt){$lt=$types.'ii';$lp=$params;$lp[]=$limit;$lp[]=$offset;$stmt->bind_param($lt,...$lp);$stmt->execute();$res=$stmt->get_result();$suppliers=$res?$res->fetch_all(MYSQLI_ASSOC):[];$stmt->close();}
$csql="SELECT COUNT(*) total FROM suppliers s {$where}"; $cstmt=$conn->prepare($csql); $totalSuppliers=0;
if($cstmt){ if($types!=='') $cstmt->bind_param($types,...$params); $cstmt->execute(); $cr=$cstmt->get_result(); $totalSuppliers=(int)(($cr&&($r=$cr->fetch_assoc()))?($r['total']??0):0); $cstmt->close(); }
$statsRes=$conn->query("SELECT COUNT(*) total_suppliers,SUM(CASE WHEN is_active=1 THEN 1 ELSE 0 END) active_suppliers,SUM(CASE WHEN is_active=0 THEN 1 ELSE 0 END) inactive_suppliers,(SELECT COUNT(DISTINCT s2.id) FROM suppliers s2 INNER JOIN remedies r2 ON s2.id=r2.supplier_id WHERE s2.is_active=1) suppliers_with_products,(SELECT COUNT(DISTINCT s3.id) FROM suppliers s3 INNER JOIN remedies r3 ON s3.id=r3.supplier_id WHERE r3.stock_quantity<=r3.reorder_level AND s3.is_active=1) low_stock_suppliers FROM suppliers");
$stats=$statsRes?$statsRes->fetch_assoc():['total_suppliers'=>0,'active_suppliers'=>0,'inactive_suppliers'=>0,'suppliers_with_products'=>0,'low_stock_suppliers'=>0];
$totalPages=max(1,(int)ceil($totalSuppliers/$limit));
$msg=$_SESSION['message']??null; unset($_SESSION['message']);
?>
<div class="top-bar">
  <h1 class="page-title"><i class="bi bi-truck"></i>Suppliers Management</h1>
  <div class="btn-toolbar d-flex gap-2">
    <button type="button" class="btn btn-outline-secondary btn-sm" onclick="printSuppliersReport()"><i class="bi bi-printer me-1"></i>Print</button>
    <button type="button" class="btn btn-primary btn-sm" onclick="openModalById('addSupplierModal')"><i class="bi bi-plus-circle me-1"></i>Add Supplier</button>
  </div>
</div>
<?php if($msg): $mt=strtolower((string)($msg['type']??'info')); $ac=$mt==='success'?'success':($mt==='error'?'danger':($mt==='warning'?'warning':'info')); ?>
<div class="alert alert-<?php echo $ac; ?> alert-dismissible fade show" role="alert"><?php echo htmlspecialchars((string)($msg['text']??'')); ?><button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>
<?php endif; ?>
<style>
.suppliers-toolbar{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.suppliers-toolbar .form-control,.suppliers-toolbar .form-select{min-width:170px;flex:1 1 220px;max-width:320px}.supplier-action-group{display:flex;flex-wrap:wrap;gap:6px;min-width:220px}.supplier-action-group .btn{min-width:34px;height:32px;padding:4px 8px;display:inline-flex;align-items:center;justify-content:center}.supplier-avatar{width:34px;height:34px;border-radius:8px;background:rgba(13,110,253,.12);color:#0d6efd;display:inline-flex;align-items:center;justify-content:center;font-size:1rem}.cursor-sort{cursor:pointer;user-select:none}.service-muted{opacity:.55;filter:grayscale(.2)}
</style>
<div class="row g-3 mb-3">
  <div class="col-md-3 col-sm-6"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="text-muted small">Total Suppliers</div><div class="fs-4 fw-semibold"><?php echo number_format((int)$stats['total_suppliers']); ?></div></div></div></div>
  <div class="col-md-3 col-sm-6"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="text-muted small">Active</div><div class="fs-4 fw-semibold"><?php echo number_format((int)$stats['active_suppliers']); ?></div></div></div></div>
  <div class="col-md-3 col-sm-6"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="text-muted small">With Products</div><div class="fs-4 fw-semibold"><?php echo number_format((int)$stats['suppliers_with_products']); ?></div></div></div></div>
  <div class="col-md-3 col-sm-6"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="text-muted small">Low Stock Alerts</div><div class="fs-4 fw-semibold"><?php echo number_format((int)$stats['low_stock_suppliers']); ?></div></div></div></div>
</div>
<div class="card border-0 shadow-sm mb-3" id="commHealthPanel"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-2"><h6 class="mb-0"><i class="bi bi-activity me-2"></i>Communication Health Check</h6><button type="button" class="btn btn-sm btn-outline-secondary" onclick="loadCommunicationHealth(true)"><i class="bi bi-arrow-clockwise me-1"></i>Refresh</button></div><div class="row g-2"><div class="col-md-6"><div class="border rounded p-2"><div class="d-flex justify-content-between align-items-center"><strong>SMTP / Email</strong><span id="smtpHealthBadge" class="badge bg-secondary">Checking...</span></div><div class="mt-1"><span id="smtpUnavailableBadge" class="badge bg-danger d-none">Email service unavailable</span></div><div id="smtpHealthDetails" class="small text-muted mt-2">Running checks...</div></div></div><div class="col-md-6"><div class="border rounded p-2"><div class="d-flex justify-content-between align-items-center"><strong>SMS</strong><span id="smsHealthBadge" class="badge bg-secondary">Checking...</span></div><div class="mt-1"><span id="smsUnavailableBadge" class="badge bg-danger d-none">SMS service unavailable</span></div><div id="smsHealthDetails" class="small text-muted mt-2">Running checks...</div></div></div></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body">
<form class="suppliers-toolbar mb-3" method="GET" action=""><input type="hidden" name="page" value="suppliers"><input type="text" class="form-control" name="search" placeholder="Search suppliers..." value="<?php echo htmlspecialchars($search); ?>"><select class="form-select" name="status" style="max-width:180px;"><option value="">All Status</option><option value="1" <?php echo $status==='1'?'selected':''; ?>>Active</option><option value="0" <?php echo $status==='0'?'selected':''; ?>>Inactive</option></select><button type="submit" class="btn btn-primary btn-sm"><i class="bi bi-check2 me-1"></i>Apply</button><a href="?page=suppliers" class="btn btn-outline-secondary btn-sm"><i class="bi bi-arrow-clockwise me-1"></i>Reset</a></form>
<div class="suppliers-toolbar mb-3"><button type="button" class="btn btn-outline-primary btn-sm" onclick="bulkActivate()"><i class="bi bi-play-circle me-1"></i>Bulk Activate</button><button type="button" class="btn btn-outline-danger btn-sm" onclick="bulkDeactivate()"><i class="bi bi-slash-circle me-1"></i>Bulk Deactivate</button><button type="button" id="bulkSendEmailBtn" class="btn btn-outline-dark btn-sm btn-email-action" onclick="bulkSendEmail()"><i class="bi bi-envelope-paper me-1"></i>Bulk Email</button><button type="button" id="bulkSendSmsBtn" class="btn btn-outline-secondary btn-sm btn-sms-action" onclick="bulkSendSMS()"><i class="bi bi-chat-left-text me-1"></i>Bulk SMS</button><?php if($isAdmin): ?><button type="button" class="btn btn-danger btn-sm" onclick="bulkDelete()"><i class="bi bi-trash me-1"></i>Bulk Delete</button><?php endif; ?></div>
<?php if(empty($suppliers)): ?><div class="alert alert-info mb-0">No suppliers found.</div><?php else: ?>
<div class="table-responsive"><table class="table table-hover align-middle" id="suppliersTable"><thead><tr><th><input type="checkbox" id="selectAll"></th><th class="cursor-sort" data-sort-col="1">ID</th><th class="cursor-sort" data-sort-col="2">Supplier</th><th class="cursor-sort" data-sort-col="3">Contact Person</th><th>Contact Info</th><th class="cursor-sort" data-sort-col="5">Products</th><th class="cursor-sort" data-sort-col="6">Status</th><th class="cursor-sort" data-sort-col="7">Created</th><th>Actions</th></tr></thead><tbody>
<?php foreach($suppliers as $s): $id=(int)$s['id']; $active=(int)$s['is_active']===1; $pc=(int)$s['product_count']; $low=(int)$s['low_stock_items']; $name=(string)($s['name']??''); $email=(string)($s['email']??''); $phone=(string)($s['phone']??''); ?>
<tr data-supplier-id="<?php echo $id; ?>"><td><input type="checkbox" class="supplier-checkbox" value="<?php echo $id; ?>"></td><td>#<?php echo $id; ?></td><td><div class="d-flex align-items-center gap-2"><span class="supplier-avatar"><i class="bi bi-building"></i></span><div><div class="fw-semibold supplier-name"><?php echo htmlspecialchars($name); ?></div><?php if($low>0): ?><small class="text-danger"><i class="bi bi-exclamation-triangle me-1"></i><?php echo $low; ?> low stock</small><?php endif; ?></div></div></td><td class="supplier-contact"><?php echo htmlspecialchars((string)($s['contact_person']??'-')); ?></td><td><div class="small"><div class="supplier-email"><?php echo htmlspecialchars($email!==''?$email:'-'); ?></div><div class="supplier-phone"><?php echo htmlspecialchars($phone!==''?$phone:'-'); ?></div></div></td><td><span class="badge <?php echo $low>0?'bg-danger':'bg-info'; ?>"><?php echo $pc; ?></span></td><td class="supplier-status"><span class="badge <?php echo $active?'bg-success':'bg-secondary'; ?>"><?php echo $active?'Active':'Inactive'; ?></span></td><td><?php echo !empty($s['created_at'])?date('M d, Y',strtotime((string)$s['created_at'])):'-'; ?></td><td><div class="supplier-action-group"><button type="button" class="btn btn-sm btn-info" onclick="viewSupplier(<?php echo $id; ?>)" title="View"><i class="bi bi-eye"></i></button><button type="button" class="btn btn-sm btn-warning text-white" onclick="editSupplier(<?php echo $id; ?>, event)" title="Edit"><i class="bi bi-pencil"></i></button><button type="button" class="btn btn-sm btn-dark btn-email-action" onclick="sendEmail('<?php echo htmlspecialchars($email,ENT_QUOTES); ?>')" title="Send Email"><i class="bi bi-envelope"></i></button><button type="button" class="btn btn-sm btn-secondary btn-sms-action" onclick="sendSMS('<?php echo htmlspecialchars($phone,ENT_QUOTES); ?>')" title="Send SMS"><i class="bi bi-chat-left-text"></i></button><button type="button" class="btn btn-sm btn-primary" onclick="printSingleSupplier(this)" title="Print Supplier"><i class="bi bi-printer"></i></button><button type="button" class="btn btn-sm <?php echo $active?'btn-outline-secondary':'btn-outline-success'; ?>" onclick="toggleSupplierStatus(<?php echo $id; ?>, <?php echo $active?1:0; ?>)" title="<?php echo $active?'Deactivate':'Activate'; ?>"><i class="bi bi-power"></i></button><?php if($isAdmin): ?><button type="button" class="btn btn-sm btn-danger" onclick="confirmDelete(<?php echo $id; ?>)" title="Delete"><i class="bi bi-trash"></i></button><?php endif; ?></div></td></tr>
<?php endforeach; ?></tbody></table></div>
<?php endif; ?>
<?php if($totalPages>1): ?><div class="d-flex justify-content-between align-items-center mt-3"><div class="text-muted small">Showing <?php echo min($offset+1,$totalSuppliers); ?> to <?php echo min($offset+$limit,$totalSuppliers); ?> of <?php echo number_format($totalSuppliers); ?> suppliers</div><nav><ul class="pagination pagination-sm mb-0"><?php for($i=1;$i<=$totalPages;$i++): ?><li class="page-item <?php echo $i===$pageNo?'active':''; ?>"><a class="page-link" href="?page=suppliers&p=<?php echo $i; ?>&search=<?php echo urlencode($search); ?>&status=<?php echo urlencode($status); ?>"><?php echo $i; ?></a></li><?php endfor; ?></ul></nav></div><?php endif; ?>
</div></div>
<?php include __DIR__ . '/modals/add_supplier.php'; include __DIR__ . '/modals/edit_supplier.php'; include __DIR__ . '/modals/view_supplier.php'; include __DIR__ . '/modals/delete_supplier.php'; ?>
<div class="modal fade" id="supplierEmailModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="bi bi-envelope me-1"></i>Send Email <span id="emailModalUnavailable" class="badge bg-danger d-none ms-2">Unavailable</span></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Email Address</label><input type="text" id="supplierEmailTo" class="form-control"></div><div class="mb-3"><label class="form-label">Subject</label><input type="text" id="supplierEmailSubject" class="form-control"></div><div class="mb-3"><label class="form-label">Message</label><textarea id="supplierEmailMessage" class="form-control" rows="6"></textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button type="button" class="btn btn-primary btn-email-action" onclick="submitEmail()">Send</button></div></div></div></div>
<div class="modal fade" id="supplierSmsModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="bi bi-chat-left-text me-1"></i>Send SMS <span id="smsModalUnavailable" class="badge bg-danger d-none ms-2">Unavailable</span></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Phone Number(s)</label><input type="text" id="supplierSmsTo" class="form-control"></div><div class="mb-3"><label class="form-label">Message</label><textarea id="supplierSmsMessage" class="form-control" rows="5"></textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button type="button" class="btn btn-primary btn-sms-action" onclick="submitSMS()">Send SMS</button></div></div></div></div>
<script>
window.SUPPLIER_AJAX_URL = 'pages/actions/ajax/supplier_actions.php';
</script>
<script src="assets/js/suppliers.js?v=<?php echo time(); ?>"></script>
